[package]
name = "miibgpd"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
