[package]
name = "miibgpd"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
bytes = "1.10.0"
rtnetlink = "0.9.0"
futures = "0.3.31"
ipnetwork = "0.18.0"
